# Generated by Django 2.2.4 on 2020-10-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_app', '0004_medicine_we_call_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='prescribed_to',
            field=models.ManyToManyField(related_name='my_meds', to='python_app.Patient'),
        ),
    ]
